import type { MenuGroup, MenuItem } from '../types/navigation.ts'

export const menuGroups: MenuGroup[] = [
  {
    title: '工作台',
    items: [
      {
        path: '/dashboard',
        view: 'dashboard/WorkbenchView',
        title: '工作台',
        icon: 'home',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/welcome',
        view: 'dashboard/WelcomeView',
        title: '欢迎页',
        icon: 'home',
        description: '',
        highlights: [],
        stage: '已启用',
        staffHome: true,
      },
    ],
  },
  {
    title: '客户管理',
    icon: 'customer',
    items: [
      {
        path: '/customers',
        view: 'customer/CustomerListView',
        title: '客户管理',
        icon: 'customer',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'customers',
      },
      {
        path: '/customer-risks',
        view: 'customer/CustomerRiskListView',
        title: '风险评估',
        icon: 'customer',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'customer-risks',
      },
      {
        path: '/customer-debts',
        view: 'customer/CustomerDebtListView',
        title: '负债登记',
        icon: 'customer',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'customer-debts',
      },
    ],
  },
  {
    title: '经营管理',
    icon: 'briefcase',
    items: [
      {
        path: '/loan-orders-self',
        view: 'loan/LoanOrderSelfListView',
        title: '借贷管理（我方）',
        icon: 'cardMoney',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'loan-orders-self',
      },
      {
        path: '/loan-orders-bank',
        view: 'loan/LoanOrderBankListView',
        title: '借贷管理（银行）',
        icon: 'cardMoney',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'loan-orders-bank',
      },
      {
        path: '/increment-details',
        view: 'loan/IncrementDetailListView',
        title: '增量详情',
        icon: 'trend',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'increment-details',
      },
      {
        path: '/opportunities',
        view: 'opportunity/OpportunityListView',
        title: '商机管理',
        icon: 'target',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'opportunities',
      },
    ],
  },
  {
    title: '经营分析',
    icon: 'chart',
    items: [
      {
        path: '/analysis/increment-overview',
        view: 'analysis/IncrementOverviewView',
        title: '增量总览',
        icon: 'chart',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'increment-overview',
      },
      {
        path: '/analysis/daily-increment',
        view: 'analysis/DailyIncrementView',
        title: '年度增量',
        icon: 'trend',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'daily-increment',
      },
      {
        path: '/analysis/performance',
        view: 'analysis/PerformanceView',
        title: '员工绩效',
        icon: 'personBadge',
        description: '',
        highlights: [],
        stage: '已启用',
        moduleKey: 'employee-performance',
      },
    ],
  },
  {
    title: '人事管理',
    icon: 'personBadge',
    items: [
      {
        path: '/hr/employees',
        view: 'hr/EmployeeListView',
        title: '员工档案',
        icon: 'personBadge',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/hr/my-profile',
        view: 'hr/MyProfileView',
        title: '我的信息',
        icon: 'personBadge',
        description: '',
        highlights: [],
        stage: '已启用',
        staffHome: true,
      },
      {
        path: '/workflow/transitions',
        view: 'workflow/TransitionApplyView',
        title: '人事异动-转正',
        icon: 'checkCard',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/workflow/salary-adjusts',
        view: 'workflow/SalaryAdjustApplyView',
        title: '人事异动-调薪',
        icon: 'cardMoney',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/hr/salaries',
        view: 'hr/SalaryManageView',
        title: '工资管理',
        icon: 'coins',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/hr/management-records',
        view: 'hr/ManagementRecordView',
        title: '管理记录',
        icon: 'document',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
    ],
  },
  {
    title: '财务管理',
    icon: 'coins',
    items: [
      {
        path: '/finance/incomes',
        view: 'finance/IncomeListView',
        title: '收入管理',
        icon: 'coins',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/finance/expenses',
        view: 'finance/ExpenseListView',
        title: '支出管理',
        icon: 'bankCard',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/finance/payees',
        view: 'finance/PayeeListView',
        title: '收款方管理',
        icon: 'wallet',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/finance/reimbursements',
        view: 'workflow/ReimbursementApplyView',
        title: '报销管理',
        icon: 'document',
        description: '',
        highlights: [],
        stage: '已启用',
      },
    ],
  },
  {
    title: '我的审批',
    icon: 'approval',
    items: [
      {
        path: '/workflow/my-approvals',
        view: 'workflow/MyApprovalView',
        title: '我的审批',
        icon: 'approval',
        description: '',
        highlights: [],
        stage: '已启用',
      },
    ],
  },
  {
    title: '系统管理',
    icon: 'gear',
    items: [
      {
        path: '/system/users',
        view: 'system/user/UserManageView',
        title: '用户管理',
        icon: 'personBadge',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/system/roles',
        view: 'system/role/RoleManageView',
        title: '角色管理',
        icon: 'gear',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/system/orgs',
        view: 'system/org/OrgManageView',
        title: '组织管理',
        icon: 'org',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
      {
        path: '/system/logs',
        view: 'system/log/OperationLogView',
        title: '管理日志',
        icon: 'document',
        description: '',
        highlights: [],
        stage: '已启用',
        requiresAdmin: true,
      },
    ],
  },
]

const flattenMenuItem = (item: MenuItem): MenuItem[] => [item, ...(item.children?.flatMap(flattenMenuItem) ?? [])]

export const flatMenuItems: MenuItem[] = menuGroups.flatMap((group) => group.items.flatMap(flattenMenuItem))
