CREATE TABLE IF NOT EXISTS `agent_action_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `trace_id` VARCHAR(64) NOT NULL COMMENT '链路追踪ID',
  `session_id` VARCHAR(128) NOT NULL COMMENT '飞书会话ID',
  `message_id` VARCHAR(128) DEFAULT NULL COMMENT '飞书消息ID',
  `scene_key` VARCHAR(64) NOT NULL COMMENT '场景标识',
  `intent_key` VARCHAR(64) NOT NULL COMMENT '意图标识',
  `tool_name` VARCHAR(128) NOT NULL COMMENT 'MCP工具名',
  `feishu_user_id` VARCHAR(128) NOT NULL COMMENT '飞书用户唯一标识',
  `feishu_display_name` VARCHAR(64) NOT NULL COMMENT '飞书展示名',
  `chat_id` VARCHAR(128) DEFAULT NULL COMMENT '飞书会话对象ID',
  `executor_user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '华彩执行账号ID',
  `executor_username` VARCHAR(64) DEFAULT NULL COMMENT '华彩执行账号',
  `target_type` VARCHAR(32) NOT NULL COMMENT '目标对象类型',
  `target_customer_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '目标客户ID',
  `target_opportunity_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '目标商机ID',
  `target_follow_record_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '目标跟进记录ID',
  `request_text` VARCHAR(4000) DEFAULT NULL COMMENT '用户原始提问',
  `request_context_json` LONGTEXT DEFAULT NULL COMMENT '请求上下文JSON',
  `tool_input_json` LONGTEXT DEFAULT NULL COMMENT '工具入参JSON',
  `extracted_payload_json` LONGTEXT DEFAULT NULL COMMENT '结构化提取结果JSON',
  `before_snapshot_json` LONGTEXT DEFAULT NULL COMMENT '执行前快照JSON',
  `confirmation_id` VARCHAR(128) DEFAULT NULL COMMENT '确认卡片ID',
  `confirmation_json` LONGTEXT DEFAULT NULL COMMENT '确认卡片JSON',
  `confirmed_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '是否已确认',
  `confirmed_at` DATETIME DEFAULT NULL COMMENT '确认时间',
  `after_snapshot_json` LONGTEXT DEFAULT NULL COMMENT '执行后快照JSON',
  `request_uri` VARCHAR(255) DEFAULT NULL COMMENT '下游请求URI',
  `request_method` VARCHAR(16) DEFAULT NULL COMMENT '下游请求方法',
  `request_body_json` LONGTEXT DEFAULT NULL COMMENT '下游请求体JSON',
  `result_code` VARCHAR(32) DEFAULT NULL COMMENT '执行结果码',
  `result_message` VARCHAR(1000) DEFAULT NULL COMMENT '执行结果说明',
  `error_message` VARCHAR(2000) DEFAULT NULL COMMENT '错误摘要',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_flag` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  `version` INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_action_log_confirmation_id` (`confirmation_id`),
  KEY `idx_agent_action_log_session_id` (`session_id`),
  KEY `idx_agent_action_log_feishu_user_id` (`feishu_user_id`),
  KEY `idx_agent_action_log_scene_key` (`scene_key`),
  KEY `idx_agent_action_log_target_customer_id` (`target_customer_id`),
  KEY `idx_agent_action_log_target_opportunity_id` (`target_opportunity_id`),
  KEY `idx_agent_action_log_target_follow_record_id` (`target_follow_record_id`),
  KEY `idx_agent_action_log_confirmation_id` (`confirmation_id`),
  KEY `idx_agent_action_log_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='飞书商机助手执行日志表';
